#!/usr/bin/env python3
"""Regenerate references/复生协议_full-tree.md for the project-structure skill.

Usage:
    python3 scripts/generate_tree.py [--project-path PATH]

Scans the 复生协议 project directory (default: ../../projects/复生协议)
and writes a complete directory tree into references/复生协议_full-tree.md.
"""
import argparse
import os
import sys

SKIP_NAMES = {".DS_Store", ".git", "__pycache__"}


def build_tree(root: str, prefix: str = "", out: list = None) -> None:
    if out is None:
        out = []
    try:
        entries = sorted(os.listdir(root))
    except OSError:
        return
    entries = [e for e in entries if e not in SKIP_NAMES]
    dirs = [e for e in entries if os.path.isdir(os.path.join(root, e))]
    files = [e for e in entries if not os.path.isdir(os.path.join(root, e))]

    for i, d in enumerate(dirs):
        last = (i == len(dirs) - 1) and not files
        out.append(prefix + ("└── " if last else "├── ") + d + "/")
        build_tree(os.path.join(root, d), prefix + ("    " if last else "│   "), out)
    for i, f in enumerate(files):
        last = (i == len(files) - 1)
        out.append(prefix + ("└── " if last else "├── ") + f)
    return out


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--project-path",
        default=os.path.join(os.path.dirname(__file__), "..", "..", "..", "projects", "复生协议"),
        help="Path to the project folder to scan",
    )
    parser.add_argument(
        "--output",
        default=os.path.join(os.path.dirname(__file__), "..", "references", "复生协议_full-tree.md"),
        help="Output markdown file",
    )
    args = parser.parse_args()

    root = os.path.abspath(args.project_path)
    if not os.path.isdir(root):
        print(f"ERROR: project path not found: {root}", file=sys.stderr)
        return 1

    lines = build_tree(root)
    header = [
        "# 复生协议 — 完整文件树",
        "",
        f"_Auto-generated by `scripts/generate_tree.py` on {os.path.basename(root)}_",
        "",
        "```",
        "复生协议/",
    ]
    body = ["    " + line if line else line for line in lines]
    footer = ["```", ""]

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        f.write("\n".join(header + body + footer))
    print(f"OK: wrote {args.output} ({len(lines)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
